name: environment_tip_generator  
channels:
  - conda-forge
dependencies:
  - pathlib
  - litellm
  - python-dotenv
  - pip
  - pdf2image
  - pytesseract
  - matplotlib
  - scikit-learn
  - scipy
  - mariadb
  - pip:
    - getpaper
    - just-agents
    - sentence-transformers
