name: environment_tip_generator
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pathlib
  - pandas
  - litellm
  - python-dotenv
  - pip
  - pdf2image
  - pytesseract
  - matplotlib
  - scikit-learn
  - scipy
  - dash
  - plotly
  - loguru
  - hdbscan
  - sqlalchemy
  - pip:
    - mariadb>=1.1.12
    - getpaper
    - just-agents
    - sentence-transformers
