name: plotly_sb
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pathlib
  - pandas
  - litellm
  - python-dotenv
  - pip
  - pdf2image
  - pytesseract
  - matplotlib
  - scikit-learn
  - scipy
  - mariadb
  - dash
  - plotly
  - loguru
  - pip:
    - getpaper
    - just-agents
    - sentence-transformers
