name: environment_tip_generator  
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pathlib
  - litellm
  - python-dotenv
  - pip
  - pdf2image
  - pytesseract
  - matplotlib
  - scikit-learn
  - scipy
  - mariadb
  - pip:
    - getpaper
    - just-agents
    - sentence-transformers
    - tkinterdnd2=0.4.2
    - customtkinter=5.2.2
    - tksheet>=7.2.23
